### ISSUE TITLE
No block given error when trying to render Highcharts SVG

### ISSUE THREAD

**Issue by KNejad** [mogest/prawn-svg#126]
I'm trying to add the following SVG generated through Highcharts server, to a PDF.

Here is the code I'm using:

```
Prawn::Document.generate('test.pdf') do
  svg res, widht: 430, height: 100
end
```
where `res` is the SVG string belong.

```
<?xml version="1.0" standalone="no"?><!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd"><svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" class="highcharts-root" style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="600" height="400"><desc>Created with Highcharts 8.1.2</desc><defs><clipPath id="highcharts-wn7ipnq-10-"><rect x="0" y="0" width="527" height="267" fill="none"></rect></clipPath><clipPath id="highcharts-wn7ipnq-14-"><rect x="0" y="0" width="527" height="267" fill="none"></rect></clipPath><clipPath id="highcharts-wn7ipnq-15-"><rect x="63" y="60" width="527" height="267" fill="none"></rect></clipPath></defs><rect fill="#ffffff" class="highcharts-background" x="0" y="0" width="600" height="400" rx="0" ry="0"></rect><rect fill="none" class="highcharts-plot-background" x="63" y="60" width="527" height="267"></rect><g class="highcharts-pane-group" data-z-index="0"></g><g class="highcharts-grid highcharts-xaxis-grid" data-z-index="1"><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 238.5 60 L 238.5 327" opacity="1"></path><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 413.5 60 L 413.5 327" opacity="1"></path><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 589.5 60 L 589.5 327" opacity="1"></path><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 62.5 60 L 62.5 327" opacity="1"></path></g><g class="highcharts-grid highcharts-yaxis-grid" data-z-index="1"><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 63 327.5 L 590 327.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 63 238.5 L 590 238.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 63 149.5 L 590 149.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 63 59.5 L 590 59.5" opacity="1"></path></g><rect fill="none" class="highcharts-plot-border" data-z-index="1" x="63" y="60" width="527" height="267"></rect><g class="highcharts-axis highcharts-xaxis" data-z-index="2"><path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="1" data-z-index="7" d="M 63 327.5 L 590 327.5"></path></g><g class="highcharts-axis highcharts-yaxis" data-z-index="2"><text x="24" data-z-index="7" text-anchor="middle" transform="translate(0,0) rotate(270 24 193.5)" class="highcharts-axis-title" style="color:#666666;fill:#666666;" y="193.5"><tspan>Values</tspan></text><path fill="none" class="highcharts-axis-line" data-z-index="7" d="M 63 60 L 63 327"></path></g><g class="highcharts-series-group" data-z-index="3"><g class="highcharts-series highcharts-series-0 highcharts-column-series highcharts-color-0" data-z-index="0.1" opacity="1" transform="translate(63,60) scale(1 1)" clip-path="url(#highcharts-wn7ipnq-14-)"><rect x="45.5" y="249.5" width="85" height="18" fill="#7cb5ec" stroke="#ffffff" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-0"></rect><rect x="220.5" y="231.5" width="85" height="36" fill="#7cb5ec" stroke="#ffffff" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-0"></rect><rect x="396.5" y="214.5" width="85" height="53" fill="#7cb5ec" stroke="#ffffff" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-0"></rect></g><g class="highcharts-markers highcharts-series-0 highcharts-column-series highcharts-color-0" data-z-index="0.1" opacity="1" transform="translate(63,60) scale(1 1)" clip-path="none"></g></g><text x="300" text-anchor="middle" class="highcharts-title" data-z-index="4" style="color:#333333;font-size:18px;fill:#333333;" y="24"><tspan>Title</tspan></text><text x="300" text-anchor="middle" class="highcharts-subtitle" data-z-index="4" style="color:#666666;fill:#666666;" y="45"><tspan>Subtitle</tspan></text><text x="10" text-anchor="start" class="highcharts-caption" data-z-index="4" style="color:#666666;fill:#666666;" y="397"></text><g class="highcharts-legend" data-z-index="7" transform="translate(259,360)"><rect fill="none" class="highcharts-legend-box" rx="0" ry="0" x="0" y="0" width="82" height="25" visibility="visible"></rect><g data-z-index="1"><g><g class="highcharts-legend-item highcharts-column-series highcharts-color-0 highcharts-series-0" data-z-index="1" transform="translate(8,3)"><text x="21" style="color:#333333;cursor:pointer;font-size:12px;font-weight:bold;fill:#333333;" text-anchor="start" data-z-index="2" y="15"><tspan>Usage</tspan></text><rect x="2" y="4" width="12" height="12" fill="#7cb5ec" rx="6" ry="6" class="highcharts-point" data-z-index="3"></rect></g></g></g></g><g class="highcharts-axis-labels highcharts-xaxis-labels" data-z-index="7"><text x="150.83333333333667" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="346" opacity="1">Jan</text><text x="326.4999999999967" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="346" opacity="1">Feb</text><text x="502.1666666666667" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="346" opacity="1">Mar</text></g><g class="highcharts-axis-labels highcharts-yaxis-labels" data-z-index="7"><text x="48" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="332" opacity="1">0</text><text x="48" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="243" opacity="1">5</text><text x="48" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="154" opacity="1">10</text><text x="48" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="65" opacity="1">15</text></g><text x="590" class="highcharts-credits" text-anchor="end" data-z-index="8" style="cursor:pointer;color:#999999;font-size:9px;fill:#999999;" y="395">Highcharts.com</text><g class="highcharts-control-points" data-z-index="99" clip-path="url(#highcharts-wn7ipnq-15-)"></g></svg>
```

This is causing the following stack trace:

```
Traceback (most recent call last):
	31: from __scrible.rb:20:in `<main>'
	30: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `generate'
	29: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document.rb:142:in `new'
	28: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document.rb:236:in `initialize'
	27: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document.rb:236:in `instance_eval'
	26: from __scrible.rb:21:in `block in <main>'
	25: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/extension.rb:19:in `svg'
	24: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:42:in `draw'
	23: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/font.rb:215:in `save_font'
	22: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:43:in `block in draw'
	21: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:157:in `bounding_box'
	20: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document/bounding_box.rb:196:in `init_bounding_box'
	19: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:44:in `block (2 levels) in draw'
	18: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/document/internals.rb:31:in `save_graphics_state'
	17: from /usr/local/bundle/gems/pdf-core-0.7.0/lib/pdf/core/renderer.rb:245:in `save_graphics_state'
	16: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:51:in `block (3 levels) in draw'
	15: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:108:in `block in proc_creator'
	14: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
	13: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `each'
	12: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:125:in `block in issue_prawn_command'
	11: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transformation.rb:82:in `translate'
	10: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transformation.rb:155:in `transformation_matrix'
	 9: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:108:in `block in proc_creator'
	 8: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
	 7: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `each'
	 6: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:125:in `block in issue_prawn_command'
	 5: from /usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transformation.rb:155:in `transformation_matrix'
	 4: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:108:in `block in proc_creator'
	 3: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `issue_prawn_command'
	 2: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:112:in `each'
	 1: from /usr/local/bundle/gems/prawn-svg-0.29.1/lib/prawn/svg/interface.rb:123:in `block in issue_prawn_command'
/usr/local/bundle/gems/prawn-2.2.2/lib/prawn/graphics/transparency.rb:62:in `transparent': no block given (yield) (LocalJumpError)
```

Note the only 2 lines which are my code in the above trace are the 2 `__scrible.rb` entries which are the lines I showed above.

I don't know what is causing this issue, but I believe it is a bug on either prawn or prawn-svg since I am passing a plain svg string which from what I understand should work.

**Comment by mogest** [comment]
Hi @KNejad, yep this is a problem with prawn-svg.  It's setting the opacity of an element and then not rendering anything inside that element, and the code doesn't like that.

I don't have time right at the moment but will go searching for a solution in the next week.  Thanks for reporting it.

**Comment by alexanderadam** [comment]
I just ran into the same issue. Is there any quick-fix?
